"""Minimal stubs for `matplotlib.pyplot` (editor only; runtime needs `pip install matplotlib`)."""

from typing import Any

def subplots(*args: Any, **kwargs: Any) -> Any: ...
def tight_layout(*args: Any, **kwargs: Any) -> None: ...
def savefig(*args: Any, **kwargs: Any) -> None: ...
def show(*args: Any, **kwargs: Any) -> None: ...
def __getattr__(name: str) -> Any: ...
