#!/usr/bin/env python3
"""Concatenate manuscript/01_*.md … 06_*.md and optionally export HTML/TeX/PDF.

Usage (from repo root):

    python3 manuscript/build_main_paper.py

`pdflatex` is a TeX Live binary (`sudo apt install texlive-latex-base pandoc`),
not a pip package. Do not `pip install pdflatex` (PEP 668 will also block it).

This script uses:
  - pandoc → main_paper.html and main_paper.tex (if pandoc is on PATH)
  - Google Chrome headless → main_paper.pdf (no TeX required)
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT_MD = HERE / "main_paper.md"
OUT_HTML = HERE / "main_paper.html"
OUT_TEX = HERE / "main_paper.tex"
OUT_PDF = HERE / "main_paper.pdf"

BANNER = """\
<!--
Concatenated manuscript. Sources: 01_title_abstract.md … 06_tables_and_figures.md.
Rebuild: python3 manuscript/build_main_paper.py
Numerical SoT: paper/frozen_results.yaml. Do not edit this file by hand.
-->

"""


def concat_markdown() -> Path:
    parts = sorted(HERE.glob("0[1-6]_*.md"))
    names = [p.name[:2] for p in parts]
    if names != ["01", "02", "03", "04", "05", "06"]:
        raise SystemExit(f"Expected 01–06 markdown parts, found: {[p.name for p in parts]}")

    chunks = [BANNER.rstrip(), ""]
    for i, path in enumerate(parts):
        body = path.read_text().rstrip() + "\n"
        if i:
            chunks.append("\n---\n")
        chunks.append(body)

    OUT_MD.write_text("\n".join(chunks) + "\n")
    print(f"Wrote {OUT_MD} ({OUT_MD.stat().st_size} bytes) from {[p.name for p in parts]}")
    return OUT_MD


def run_pandoc(src: Path) -> None:
    pandoc = shutil.which("pandoc")
    if not pandoc:
        print("pandoc not found; skip HTML/TeX. Install: sudo apt install pandoc")
        return
    subprocess.run(
        [
            pandoc,
            str(src),
            "--from",
            "markdown",
            "--standalone",
            "--metadata",
            "title=VLST after ACS-PCI",
            "--embed-resources",
            "--resource-path",
            f"{HERE}:{HERE.parent}",
            "--to",
            "html5",
            "--output",
            str(OUT_HTML),
        ],
        check=True,
    )
    print(f"Wrote {OUT_HTML}")
    subprocess.run(
        [
            pandoc,
            str(src),
            "--from",
            "markdown",
            "--standalone",
            "--to",
            "latex",
            "--output",
            str(OUT_TEX),
        ],
        check=True,
    )
    print(f"Wrote {OUT_TEX} (source only; compile later with pdflatex if TeX Live is installed)")


def chrome_pdf() -> None:
    if not OUT_HTML.exists():
        print("No HTML; skip PDF")
        return
    chrome = shutil.which("google-chrome") or shutil.which("chromium") or shutil.which("chromium-browser")
    if not chrome:
        print("Chrome/Chromium not found; skip PDF")
        return
    uri = OUT_HTML.resolve().as_uri()
    cmd = [
        chrome,
        "--headless=new",
        "--disable-gpu",
        "--no-pdf-header-footer",
        f"--print-to-pdf={OUT_PDF}",
        uri,
    ]
    # Sandboxes often forbid Chrome's own sandbox.
    cmd.insert(1, "--no-sandbox")
    subprocess.run(cmd, check=True)
    print(f"Wrote {OUT_PDF} ({OUT_PDF.stat().st_size} bytes)")


def main() -> None:
    concat_markdown()
    run_pandoc(OUT_MD)
    chrome_pdf()


if __name__ == "__main__":
    main()
